# Generated by Django 4.2.5 on 2023-09-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_vehiculos', '0002_vehiculo_remove_producto_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='serial_carroceria',
            field=models.CharField(max_length=50),
        ),
    ]
